### ISSUE TITLE
Managing the API endpoints

### ISSUE THREAD

**Issue by yagozk** [Project-Yicem/Yicem-backend#24]
While the frontend-backend connection is being established, make necessary changes (add new endpoints, update existing ones etc.) as needed.

**Comment by yagozk** [comment]
- [ ] There should be separate "openingTime" and "closingTime" attributes in a business, not a "workingHours" attribute
- [ ] Implement "isOpen" as an attribute of a business. This will be calculated for each business as a boolean whenever the endpoint for getting all businesses (/api/buyer/view-businesses) is called.
- [ ] An offer should have a list of pickup options, e.g. pickUpTimeOptions: ["16.00-17.00", "17.00-18.00"...] 
- [ ] Change the "mark offer as sold" logic as we discussed before. (See the top of the google docs for APIs)
- [ ] Something wrong with the id field when adding an offer (check the screenshots in the groupchat for this)

**Comment by egecenberci** [comment]
Check commit 3f1c8e1356ba584a12ffeddca12aff684a0de06f to see changes made to update MarkSold.

**Comment by Bilgehansandikci** [comment]
- [ ] after seller/update updates seller, get seller/{seller} does not work.
- [ ] authorization in get seller/{seller}, currently any id passed, returns its userdata
- [ ] in seller/{seller}/offers, there is only reservationID returned in reservations field for the offer. reservationTime and customer name should also be included.
- [ ] /api/seller/{seller}/history only returns transactionIDs, if exists, comment & rating, customerName, date, offername atc should be returned.

**Comment by oburakdogan** [comment]
> * [x]  authorization in get seller/{seller}, currently any id passed, returns its userdata
- This is not a problem, it only gets public seller info for now.
